version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo Installing dependencies...
      - pip3 install -r requirements.txt
  pre_build:
    commands:
      - echo Running Django migrations...
      - python3 manage.py migrate
  build:
    commands:
      - echo Running Django tests...
      - python3 manage.py test
artifacts:
  files:
    - '**/*'
